# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PollCreate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'title': 'str',
        'creator_id': 'str',
        'expiration_time': 'datetime',
        'short_description': 'str',
        'long_description': 'str',
        'choices': 'list[str]'
    }

    attribute_map = {
        'title': 'title',
        'creator_id': 'creator_id',
        'expiration_time': 'expiration_time',
        'short_description': 'short_description',
        'long_description': 'long_description',
        'choices': 'choices'
    }

    def __init__(self, title=None, creator_id=None, expiration_time=None, short_description=None, long_description=None, choices=None):  # noqa: E501
        """PollCreate - a model defined in Swagger"""  # noqa: E501
        self._title = None
        self._creator_id = None
        self._expiration_time = None
        self._short_description = None
        self._long_description = None
        self._choices = None
        self.discriminator = None
        self.title = title
        self.creator_id = creator_id
        self.expiration_time = expiration_time
        self.short_description = short_description
        self.long_description = long_description
        self.choices = choices

    @property
    def title(self):
        """Gets the title of this PollCreate.  # noqa: E501


        :return: The title of this PollCreate.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this PollCreate.


        :param title: The title of this PollCreate.  # noqa: E501
        :type: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def creator_id(self):
        """Gets the creator_id of this PollCreate.  # noqa: E501


        :return: The creator_id of this PollCreate.  # noqa: E501
        :rtype: str
        """
        return self._creator_id

    @creator_id.setter
    def creator_id(self, creator_id):
        """Sets the creator_id of this PollCreate.


        :param creator_id: The creator_id of this PollCreate.  # noqa: E501
        :type: str
        """
        if creator_id is None:
            raise ValueError("Invalid value for `creator_id`, must not be `None`")  # noqa: E501

        self._creator_id = creator_id

    @property
    def expiration_time(self):
        """Gets the expiration_time of this PollCreate.  # noqa: E501


        :return: The expiration_time of this PollCreate.  # noqa: E501
        :rtype: datetime
        """
        return self._expiration_time

    @expiration_time.setter
    def expiration_time(self, expiration_time):
        """Sets the expiration_time of this PollCreate.


        :param expiration_time: The expiration_time of this PollCreate.  # noqa: E501
        :type: datetime
        """
        if expiration_time is None:
            raise ValueError("Invalid value for `expiration_time`, must not be `None`")  # noqa: E501

        self._expiration_time = expiration_time

    @property
    def short_description(self):
        """Gets the short_description of this PollCreate.  # noqa: E501


        :return: The short_description of this PollCreate.  # noqa: E501
        :rtype: str
        """
        return self._short_description

    @short_description.setter
    def short_description(self, short_description):
        """Sets the short_description of this PollCreate.


        :param short_description: The short_description of this PollCreate.  # noqa: E501
        :type: str
        """
        if short_description is None:
            raise ValueError("Invalid value for `short_description`, must not be `None`")  # noqa: E501

        self._short_description = short_description

    @property
    def long_description(self):
        """Gets the long_description of this PollCreate.  # noqa: E501


        :return: The long_description of this PollCreate.  # noqa: E501
        :rtype: str
        """
        return self._long_description

    @long_description.setter
    def long_description(self, long_description):
        """Sets the long_description of this PollCreate.


        :param long_description: The long_description of this PollCreate.  # noqa: E501
        :type: str
        """
        if long_description is None:
            raise ValueError("Invalid value for `long_description`, must not be `None`")  # noqa: E501

        self._long_description = long_description

    @property
    def choices(self):
        """Gets the choices of this PollCreate.  # noqa: E501


        :return: The choices of this PollCreate.  # noqa: E501
        :rtype: list[str]
        """
        return self._choices

    @choices.setter
    def choices(self, choices):
        """Sets the choices of this PollCreate.


        :param choices: The choices of this PollCreate.  # noqa: E501
        :type: list[str]
        """
        if choices is None:
            raise ValueError("Invalid value for `choices`, must not be `None`")  # noqa: E501

        self._choices = choices

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PollCreate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PollCreate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
