# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class VoteSummaryChoices(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'choice': 'Choice',
        'total_votes': 'int'
    }

    attribute_map = {
        'choice': 'choice',
        'total_votes': 'total_votes'
    }

    def __init__(self, choice=None, total_votes=None):  # noqa: E501
        """VoteSummaryChoices - a model defined in Swagger"""  # noqa: E501
        self._choice = None
        self._total_votes = None
        self.discriminator = None
        self.choice = choice
        self.total_votes = total_votes

    @property
    def choice(self):
        """Gets the choice of this VoteSummaryChoices.  # noqa: E501


        :return: The choice of this VoteSummaryChoices.  # noqa: E501
        :rtype: Choice
        """
        return self._choice

    @choice.setter
    def choice(self, choice):
        """Sets the choice of this VoteSummaryChoices.


        :param choice: The choice of this VoteSummaryChoices.  # noqa: E501
        :type: Choice
        """
        if choice is None:
            raise ValueError("Invalid value for `choice`, must not be `None`")  # noqa: E501

        self._choice = choice

    @property
    def total_votes(self):
        """Gets the total_votes of this VoteSummaryChoices.  # noqa: E501


        :return: The total_votes of this VoteSummaryChoices.  # noqa: E501
        :rtype: int
        """
        return self._total_votes

    @total_votes.setter
    def total_votes(self, total_votes):
        """Sets the total_votes of this VoteSummaryChoices.


        :param total_votes: The total_votes of this VoteSummaryChoices.  # noqa: E501
        :type: int
        """
        if total_votes is None:
            raise ValueError("Invalid value for `total_votes`, must not be `None`")  # noqa: E501

        self._total_votes = total_votes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VoteSummaryChoices, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VoteSummaryChoices):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
