apiVersion: v1
kind: Service
metadata:
  name: learn-k8s-webapp-service
  labels:
    app: learn-k8s-webapp
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: learn-k8s-webapp
  ports:
    - name: http
      port: 80
      targetPort: 80